public with sharing class someDraftArticle extends AbstractArticle {

    public integer MyMethod () { 
        while(true){
            insert newAcct;
        }

        for(Accts newAcct : listAccts){
           merge newAcct super.oldAcct; 
        }
    }

    public DraftArticle(){
            insert newAcct;
    }

    @deprecated    
    public void myInit(){
        integer max = 10;
    }
}


    