public with sharing class draftArticle extends AbstractArticle {

    public integer MyMethod () { 
        while(trueExpression){
            insert newAcct;
        }

        for(Accts newAcct : listAccts){
           merge newAcct; 
        }
    }

    public DraftArticle(){
            insert newAcct;
    }

    @deprecated    
    public void myInit(){
        integer max = 10;
    }
}


    