public with sharing class someDraftArticle extends AbstractArticle {

    public integer MYmeThod () { 
        while(true){
            insert newAcct;
        }

        for(Accts newAcct : listAccts){
           merge newAcct super.oldAcct; 
        }
    }

    public DraftArticle(){
            insert newAcct;
    }

    @deprecated    
    public void myINIT(){
        integer max = 10;
    }

    public deleteArticle(){
            DELETE newAcct;
    }
    
    public integer deleteArticle(integer arg1, integer arg2, integer arg3, integer arg4, integer arg5, integer arg6){
            return null
    }
    
    public someDraftArticle(integer arg1, integer arg2, integer arg3, integer arg4, integer arg5, integer arg6){
    	
    }
}


    