public class demostrationClass {
    
    public demostrationClass(Account account) {
        while(account.getRecordType == '4654134167168118') {

        }
    }
    private VOID something (ID someId) {
       String id = '546546455454654AWB';
       for (Account a : accountCreator.getList) {
            if('65469451346546135' == a.RecordTypeId) {
            
            }
       }
       something('554546546465456');
    }
}

