public class DraftArticle {
    
    private static final ID firsRecordId = '00015CHARACTERS';
    
    private static final String fakeRecordId = '00015CHARACTERS';

    private ID recordId;
    
    public void someMethod() {
        recordId = '012500000009WAr';

        Id secondRecord = '123588544566959';

        String anotherFakeRecordId = '00018abcCHARACTERS';

        boolean isActive = true;
    }
}
