public class Foo {
	public void bar() { 
		if (true) {
			if(true){ try{}Catch(){}
			}
			if (true) {
				if (true) {
				}
			}
			if(true) {
				if(true) {
					if(true) {
					}
				}
				if(true) {
				}
				if(true) {
				}
			}
			if(true){
			}
		}
		
		if (true) {
			if(true){ try{}Catch(){}
			}
			if (true) {
				if (true) {
				}
			}
			if(true) {
				if(true) {
					if(true) {
					}
				}
				if(true) {
				}
				if(true) {
				}
			}
			if(true){
			}
		}else if(true){
			if(true){
				if(true){
				
				}
			}
		}
	}
}
