public with sharing class SampleClass{

    public integer MYmeThod () { 
        while(true){
            insert newAcct;
        }

        for(Accts newAcct : listAccts){
           merge newAcct super.oldAcct; 
        }
    }

    public SampleClass(){
            insert newAcct;
    }
    
    public void SampleClass () { 
        for(Accts newAcct : listAccts){
           merge newAcct super.oldAcct; 
        }
    }
    
    private SampleClass () { 
        for(Accts newAcct : listAccts){
           merge newAcct super.oldAcct; 
        }
    }
    
    public integer SampleClass () { 
        for(Accts newAcct : listAccts){
           merge newAcct super.oldAcct; 
        }
    }
}