public with sharing class SampleClass{
 
    public integer prop1 {get;set;}
    public string prop2 {get;set;}
    public integer prop3 {get;set;}
    List<Account> lstAccount;
    Map<id, Account> mapAcc;
    public Set<String> AccountIds {get;set;}
    public integer prop;

    public integer MYmeThod () { 
        while(true){
            insert newAcct;
        }

        for(Accts newAcct : listAccts){
           merge newAcct super.oldAcct; 
        }
    }

    public SampleClass(){
            insert newAcct;
    }
    
    public void SampleClass () { 
        for(Accts newAcct : listAccts){
           merge newAcct super.oldAcct; 
        }
    }
    
    private SampleClass () { 
        for(Accts newAcct : listAccts){
           merge newAcct super.oldAcct; 
        }
    }
    
    public integer SampleClass () { 
        for(Accts newAcct : listAccts){
           merge newAcct super.oldAcct; 
        }
    }
}