public class ApexClass_0 extends anotherClass{
    public static string method1() {
        if(value != anotherValue) {
        } else {
        }
    }

    public integer calculate(integer addition, int takeAway, Display display) {
        if (true == display.invokeSomeMethod()) {
            takeAway.isAlwaysAvailable();
        } else {
            ApexClass_0.method1();
        }
        assertTrue(display.isInvisible());
    }
}
